import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const sportingGrotesque = localFont({
  src: [
    {
      path: "../../public/fonts/SportingGrotesque-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/SportingGrotesque-Bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-sporting-grotesque",
  display: "swap",
});

export const metadata: Metadata = {
  title: "DEVLOP.ME",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sportingGrotesque.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
